name: Get Citation Data

on:
  page_build:
  workflow_dispatch:          # ✅ 手动触发按钮
  schedule:
    - cron: '0 8 * * *'       # ✅ 每天 8:00 UTC 自动执行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Reqs
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip python3-setuptools -y
          pip3 install -r google_scholar_crawler/requirements.txt

      - name: Run
        env:
          GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
        run: |
          cd ./google_scholar_crawler
          python3 main.py
          cd ../results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "blueprintf@gmail.com"
          git add *.json
          git commit -m "Updated Citation Data"
          git push --force "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:google-scholar-stats
